### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by le2Ks** [falconivity-project/falconivity#1]
Hello!

We can't download the blockchain, it has the headers sync but it get stuck to download the blocks.
There is an error in the debug.log saying that there are several forks on the same network.

Could you provide a snapshot of the actual chain (at block height 1,118) pls, that would fix it, ty!

**Comment by falconivity-project** [comment]
on the website https://falconivity.com under resources section, you can find "Snapshot of the blockchain" file to download

**Comment by falconivity-project** [comment]
I will be adding the latest snapshots to the site, this should solve the problem

**Comment by le2Ks** [comment]
> I will be adding the latest snapshots to the site, this should solve the problem

Hello, no it did not fix it.

It missed all chainstate and other files for the blocks.

It should look like this, the two folders "blocks" and "chainstate" will make a snapshot
<p align="center"> 
  <img width="336" height="227"  src="https://i.imgur.com/NycALxR.png">
  <img width="200" height="100" src="https://i.imgur.com/x27kJgo.png">
</p>
ty!

**Comment by falconivity-project** [comment]
you're right, it's fixed

**Comment by le2Ks** [comment]
It<s a bit too late lol
